services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: sync
          path: ./components
          target: /app/components
        - action: rebuild
          path: package.json